version: "3.3"
services:
  mongo:
    image: mongo
    expose:
      - 27017
    command: --quiet
    volumes:
      - mongodbdata:/data/db

  # Message queue required by Celery
  rabbitmq:
     image: rabbitmq:3.8-management
     restart: always
     env_file:
       - .env
     ports:
       - "5672:5672"
       - "15672:15672"

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
    env_file:
      - .env

  api:
    build: ./backend
    ports:
      - "443:443"
    depends_on:
      - mongo
      - neo4j
      - minio
    volumes:
      - ./backend:/backend
    command:  sh -c "./wait && ./start.sh"
    restart: always
    tty: true
    privileged: true
    environment:
      WAIT_HOSTS: mongo:27017, neo4j:7474, neo4j:7687, minio:9000
    env_file:
      - .env

  # Celery worker that does schema matching jobs
  celery-worker:
    build: ./backend
    volumes:
      - ./backend:/backend
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: celery -A backend.app.celery worker -l INFO --concurrency=2 --max-memory-per-child=2929687
    depends_on:
      - rabbitmq

  # Celery Flower dashboard
  celery-flower:
    build: ./backend
    volumes:
      - ./backend:/backend
    command: "celery -A backend.app.celery flower --broker_api=http://rabbitmq:rabbitmq@rabbitmq:15672/api/"
    restart: always
    environment:
      - FLOWER_PORT=5555
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - celery-worker

  redis:
    image: redis:latest
    env_file:
      - .env
    command: redis-server --requirepass redis --maxmemory 512mb
    ports:
      - "6379:6379"

  # Profiler which determines the primary-key foreign-key constraints
  metanome:
   # base_image: # Only supported in docker-compose 3.9...
   #   profiles:
   #     - metanome
   build: ./metanome
   expose:
     - 443
   ports:
     - "8080:8080"
   volumes:
     - ./metanome/src:/src
     - ./metanome/logs:/logs
   command:  sh -c "./start"
   restart: always
   tty: true
   privileged: true
   environment:
     WAIT_HOSTS: mongo:27017, elastic:9200, neo4j:7474, neo4j:7687
   env_file:
     - .env

  # S3-like object store holding the data that we want to match
  minio:
    image: "minio/minio"
    command: minio server --console-address :9001 /data
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "miniodata:/data"
    env_file:
      - .env

volumes:
  miniodata:
  mongodbdata:
  neo4jdata:
