version: "3.3"
services:

  # Message queue required by Celery for distributed messaging between the workers
  rabbitmq:
     image: rabbitmq:3.8
     restart: always
     env_file:
        - .env
     expose:
       - 5672

  # Graph database used for discovery
  neo4j:
    image: neo4j
    expose:
      - 7474
      - 7687
    volumes:
      - neo4jdata:/data
    env_file:
      - .env

  # API for public access
  api:
    build: ./backend
    ports:
      - "443:443"
    depends_on:
      - neo4j
    volumes:
      - data:/data
    command:  sh -c "./wait && ./start.sh"
    restart: always
    tty: true
    privileged: true
    environment:
      WAIT_HOSTS: neo4j:7474, neo4j:7687
      PYTHONUNBUFFERED: 1
    env_file:
      - .env

  # Celery worker that does schema matching jobs
  celery-worker:
    build: ./backend
    volumes:
      - data:/data
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    command: celery -A backend.celery worker -l INFO --concurrency=1
    depends_on:
      - rabbitmq

  # Celery beat, used for  scheduling
  celery-beat:
    build: ./backend
    volumes:
      - data:/data
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    command: celery -A backend.celery beat -l INFO
    depends_on:
      - rabbitmq

  # In-memory store with persistence used for storing daisy table metadata and celery task information/statuses
  redis:
    image: redis/redis-stack-server:latest
    environment:
      REDIS_ARGS: --maxmemory 512mb --requirepass redis
    env_file:
      - .env
    expose:
      - 6379
    volumes:
      - redisdata:/data

  # Profiler which determines the primary-key foreign-key constraints
  metanome:
   build: ./metanome
   expose:
     - 443
   volumes:
     - data:/metanome/backend/WEB-INF/classes/inputData
   command:  sh -c "./start"
   restart: always
   tty: true
   privileged: true
   environment:
     WAIT_HOSTS: neo4j:7474, neo4j:7687
   env_file:
     - .env

volumes:
  neo4jdata:
  redisdata:
  data:
