version: "3.3"
services:
  # Message queue required by Celery
  rabbitmq:
     image: rabbitmq:3.8-management
     restart: always
     env_file:
       - .env
       - .config
     ports:
       - "5672:5672"
       - "15672:15672"

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
    env_file:
      - .env
      - .config

  api:
    build: ./backend
    ports:
      - "443:443"
    depends_on:
      - neo4j
    volumes:
      - ./backend:/backend
      - ./backend/logs:/logs
      - data:/data
    command:  sh -c "./wait && ./start.sh"
    restart: always
    tty: true
    privileged: true
    environment:
      WAIT_HOSTS: neo4j:7474, neo4j:7687
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
      - .config

  # Celery worker that does schema matching jobs
  celery-worker:
    build: ./backend
    volumes:
      - ./backend:/backend
      - data:/data
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
      - .config
    # Polling is required because inotify does not work on subfolders of bind mounts
    command: watchmedo auto-restart --debug-force-polling -d /backend/utility/celery_tasks.py -d /backend/__init__.py -- celery -A backend.celery worker -l INFO --concurrency=1
    depends_on:
      - rabbitmq

  # Celery Flower dashboard
  celery-flower:
    build: ./backend
    volumes:
      - ./backend:/backend
    command: "celery -A backend.celery flower --broker_api=http://rabbitmq:rabbitmq@rabbitmq:15672/api/"
    restart: always
    environment:
      - FLOWER_PORT=5555
    env_file:
      - .env
      - .config
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - celery-worker

  redis:
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--maxmemory 512mb --requirepass redis
    env_file:
      - .env
      - .config
    ports:
      - "6379:6379"
      - "8001:8001"    
    volumes:
      - redisdata:/data

  # Profiler which determines the primary-key foreign-key constraints
  metanome:
   build: ./metanome
   expose:
     - 443
   ports:
     - "8080:8080"
   volumes:
     - ./metanome/src:/src
     - ./metanome/logs:/logs
     - data:/data
   command:  sh -c "./start"
   restart: always
   tty: true
   privileged: true
   environment:
     WAIT_HOSTS: neo4j:7474, neo4j:7687
   env_file:
     - .env
     - .config

volumes:
  redisdata:
  neo4jdata:
  data:
